version: '2'
services:
    nginx:
        image: nginx:stable
        volumes:
            - ./nginx/it:/etc/nginx/conf.d
#            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#            - ./nginx/mime.types:/etc/nginx/mime.types
            - ./nginx/logs:/var/log/nginx
        ports:
            - "80:80"
        volumes_from:
            - drupal
        links:
          - drupal
    drupal:
        image: drupal:8.4-fpm
#    mysql:
#        image: mysql:5
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_DATABASE: drupal
#            MYSQL_ROOT_PASSWORD: secret
